### ISSUE TITLE
Customize list style

### ISSUE THREAD

**Issue by ManUtopiK** [ocavue/prosemirror-flat-list#234]
It's quite hard to customize the list style. Particularly targeting the last item of a list.

![image](https://github.com/user-attachments/assets/9a715600-e240-45a5-b312-58cd12a25236)
I can target the first `.prosemirror-flat-list` item to add a `padding-top`, but how to target the last item of a list ?

It will be nice to add some `.first` and `.last` classes to easily customize the list.

**Comment by ocavue** [comment]
It would be difficult to add something like `.first` and `.last` classes, because when the list node is rendering (i.e. calling `toDOM()` function), it doesn't known its position or its siblings. 

You can implement this with CSS `:has()`. 

```css
.prosemirror-flat-list {
  color: red;
}

.prosemirror-flat-list + .prosemirror-flat-list {
  color: gray;
}

.prosemirror-flat-list:not(:has(+ .prosemirror-flat-list)) {
  color: blue;
}
```

<img width="1170" alt="image" src="https://github.com/user-attachments/assets/a946d154-e308-4122-8097-497d33abdab9">

**Comment by ocavue** [comment]
Here is another example where you can also match the last list item in a sequence of list items **with the same kind**.

```css

.prosemirror-flat-list[data-list-kind='ordered'] {
  color: orange;
}
.prosemirror-flat-list[data-list-kind='bullet'] {
  color: purple;
}


.prosemirror-flat-list[data-list-kind='ordered']
  + .prosemirror-flat-list[data-list-kind='ordered'],
.prosemirror-flat-list[data-list-kind='bullet']
  + .prosemirror-flat-list[data-list-kind='bullet'] {
  color: gray;
}

.prosemirror-flat-list[data-list-kind='ordered']:not(
    :has(+ .prosemirror-flat-list[data-list-kind='ordered'])
  ) {
  color: blue;
}
.prosemirror-flat-list[data-list-kind='bullet']:not(
    :has(+ .prosemirror-flat-list[data-list-kind='bullet'])
  ) {
  color: lightblue;
}
```

<img width="1181" alt="image" src="https://github.com/user-attachments/assets/8ea863ec-7a75-4ecd-a16e-ed67d3e6d2e6">


Online playground: https://stackblitz.com/edit/github-vswmhr?file=style-list.css
